defaults:
  - model: soundstream
  - metrics: soundstream
  - datasets: librispeech_eval
  - dataloader: soundstream
  - transforms: null
  - _self_

inferencer:
  device: auto
  seed: 1
  save_path: "predictions"
  from_pretrained: "soundstream_libri/model_best.pth"
  device_tensors: [ "audio" ]

transforms:
  batch_transforms:
    train: null
    inference: null

datasets:
  test:
    _target_: src.datasets.libri_speech.LibriSpeechDataset
    root_dir: "data"
    url: "test-clean"
    sample_rate: 16000
    crop: null
