defaults:
  - model: soundstream
  - writer: cometml
  - metrics: soundstream
  - datasets: librispeech
  - dataloader: soundstream
  - transforms: null
  - _self_

optimizer:
  _target_: torch.optim.Adam
  lr: 0.0002
  betas: [ 0.5, 0.9 ]

optimizer_d:
  _target_: torch.optim.Adam
  lr: 0.0002
  betas: [ 0.5, 0.9 ]

lr_scheduler:
  _target_: torch.optim.lr_scheduler.ConstantLR
  factor: 1.0
  total_iters: 999999

criterion:
  _target_: src.loss.generator_loss.GeneratorLoss
  lambda_commit: 1.0
  lambda_feat: 100.0

discriminator:
  _target_: src.model.discriminator.Discriminator

transforms:
  batch_transforms:
    train: null
    inference: null

writer:
  run_name: "SoundStream"

trainer:
  log_step: 50
  n_epochs: 50
  epoch_len: 900
  device_tensors: [ "audio" ]
  resume_from: null
  device: auto
  override: True
  monitor: "max val_STOI"
  save_period: 5
  early_stop: 50
  save_dir: "saved"
  seed: 1
  max_grad_norm: 10.0
