_target_: src.logger.cometml.CometMLWriter
project_name: "bhw-soundstream-plotnikov244"
workspace: null
run_name: "SoundStream-6kbps"
mode: "online"
loss_names: [
  "loss",
  "discriminator_loss",
  "adversarial_loss",
  "feature_loss",
  "reconstruction_loss",
  "commitment_loss",
  "codebook_perplexity",
]
log_checkpoints: True
id_length: 32
