_target_: src.logger.CometMLWriter
project_name: "bhw-soundstream-plotnikov244"
workspace: null
run_name: "testing"
mode: "online"
loss_names: [ "adversarial loss",
              "feature loss",
              "reconstruction loss",
              "commitment loss",
              "generator_loss",
              "discriminator_loss",
              "codebook_perplexity" ] # which losses to log (useful for multi-loss tasks, s.a. GANs)
log_checkpoints: True # set to True if you want to log save_dir with checkpoints to W&B
id_length: 32 # length of the run_id
